const bookArray = [
   {
      asin: "B002CSL0BQ",
      price: 1.01,
      title: "Storm Front: The Dresden Files, Book 1",
      image: "https://m.media-amazon.com/images/I/51Nz4frJQmL._AC_UL320_.jpg",
      desc: "My name is Harry Blackstone Copperfield Dresden. Conjure by it at your own risk. I'm a wizard. I work out of an office in midtown Chicago. As far as I know, I'm the only openly practicing professional wizard in the country. You can find me in the yellow pages, under Wizards. Believe it or not, I'm the only one there.  With rent past due and a decent meal becoming an issue of some importance, Harry needs work, and soon. A call from a distraught wife, and another from Lt. Murphy of the Chicago PD Special Investigation Unit makes Harry believe things are looking up, but they are about to get worse, much worse. Someone is harnessing immense supernatural forces to commit a series of grisly murders. Someone has violated the first law of magic: Thou Shalt Not Kill. Tracking that someone takes Harry into the dangerous underbelly of Chicago, from mobsters to vampires, while he himself is under suspicion of the crimes.",
   },
   {
      asin: "B002CSL0CA",
      price: 2.02,
      title: "Fool Moon: The Dresden Files, Book 2",
      image: "https://m.media-amazon.com/images/I/51gfXLJgqcL.jpg",
      desc: "Harry Blackstone Copperfield Dresden is Chicago's only openly practicing wizard. He is also dead broke. His vast knowledge and magical skills are unfortunately matched by his talent for making powerful enemies and alienating friends. With little more than his integrity left, he accepts an offer of work from Lt. Karin Murphy of Chicago's Special Investigations Unit. He wants to redeem himself in Murphy's eyes and make enough money to quiet his rumbling stomach.  Soon he finds himself pinned between trigger-happy FBI agents, shape-shifiting motorcycle gang members, a threatened mobster boss, and an heir to an ancient curse along with his primal fiance. Throw in environmental activists and a pair of young werewolves in love and you have something of Fool Moon.",
   },
   {
      asin: "B002CSL0CK",
      price: 3.03,
      title: "Grave Peril: The Dresden Files, Book 3",
      image: "https://m.media-amazon.com/images/I/51eSe1t9ojL._AC_UL320_.jpg",
      desc: "Harry Blackstone Copperfield Dresden has had a rough couple of weeks. As the only openly practicing professional wizard in the Chicago area, he has squared off against a multitude of supernatural bad guys. Harry has won the day against demons, poltergeists, sorcerers, trolls, vampires, werewolves, and even an evil faerie godmother. You might think nothing could spook him. You would be wrong.  Something is stirring up angry apparitions all over town. Something that can break all the laws of supernatural physics. Something that doesnt like Harry. His closest friends are being targeted. The net is closing in. Harry must find a solution soon or find this is one Nightmare from which he will never waken.",
   },
   {
      asin: "B002CSL0C0",
      price: 4.04,
      title: "Summer Knight: The Dresden Files, Book 4",
      image: "https://m.media-amazon.com/images/I/51dE7lwVKIL.jpg",
      desc: "Harry Blackstone Copperfield Dresden is a very powerful wizard and a dedicated private eye. He is also a wise cracking trouble magnet. Fueled by a tempest of guilt, sleep deprivation, malnutrition, bad temper and frankly awful personal grooming. Harry is hurtling toward oblivion. According to Harry that is nobody's business but his own.  The Winter Queen of Faerie manipulates him into accepting a case to solve a murder and stop a war between the courts of Summer and Winter that could have literally earth shattering consequences. His own soul is up for grabs. Dresden must dig deep to discover that at time a willingness to accept a little help from your friends, be they a cub pack of werewolves, old loves in sheep's clothing, or a battalion of pizza loving dewdrop fairies, is a very good thing.",
   },
   {
      asin: "B002UUDFD2",
      price: 5.05,
      title: "Death Masks: The Dresden Files, Book 5",
      image: "https://m.media-amazon.com/images/I/51FdTSbdGCL.jpg",
      desc: "Harry Dresden, Chicago's only practicing professional wizard, should be happy that business is pretty good for a change. But he also knows that whenever things are going good, the only way left for them to go is bad. Way bad. Recent examples: A duel with the lethal champion of the Red Court, who must kill Harry to end the war between vampires and wizards...Hit men using Harry for target practice...The missing Shroud of Turin - and the possible involvement of Chicago's most feared mob boss...A handless and headless corpse the Chicago police need identified...Not to mention the return of Harry's ex-girlfriend Susan, who's still struggling with her semi-vampiric nature - and who seems to have a new man in her life. Some days, it just doesn't pay to get out of bed. No matter how much you're charging.",
   },
   {
      asin: "B003CN7DQ6",
      price: 6.06,
      title: "Blood Rites: The Dresden Files, Book 6",
      image: "https://m.media-amazon.com/images/I/61KPkEAV6XL.jpg",
      desc: "Harry Dresden, Chicago's only professional wizard, takes on a case as a favor to his friend Thomas - a vampire of dubious integrity - only to become the prime suspect in a series of ghastly murders.",
   },
   {
      asin: "B003CN7EEC",
      price: 7.07,
      title: "Dead Beat: The Dresden Files, Book 7",
      image: "https://m.media-amazon.com/images/I/615v5uDCYeL.jpg",
      desc: "When a killer vampire threatens to destroy head of Special Investigations Karrin Murphy's reputation, unless Harry delivers the powerful Word of Kemmler to her, he has no choice. Now Harry is in a race against time to find the Word before Chicago experiences a Halloween night to wake the dead.",
   },
   {
      asin: "B0027IQ5O8",
      price: 8.08,
      title: "Proven Guilty: The Dresden Files, Book 8",
      image: "https://m.media-amazon.com/images/I/51oPPtWwa-L.jpg",
      desc: "The White Council of Wizards has drafted Harry Dresden as a Warden and assigned him to look into rumors of black magic in Chicago. Malevolent entities that feed on fear are loose in the Windy City, but it's all in a day's work for a wizard, his faithful dog, and a talking skull named Bob.",
   },
   {
      asin: "B0027USLT8",
      price: 9.09,
      title: "White Night: The Dresden Files, Book 9",
      image: "https://m.media-amazon.com/images/I/51Xj+vH43ZL.jpg",
      desc: "Meet Harry Dresden, Chicago's first (and only) Wizard P.I. Turns out the 'everyday' world is full of strange and magical things - and most of them don't play well with humans. That's where Harry comes in.A series of apparent suicides rings alarm bells with the police, and Harry is hired. At the first crime scene he hits pay dirt, discovering an unmistakable magical taint. There's also a message especially for him, and it ain't pretty. The 'killings' will continue if Harry can't halt his tormentor, but the evidence implicates his half-brother, which just doesn't add up. Unfortunately Harry's digging around attracts some powerful vampires with a stake in the result. Soon, whichever way he turns, Harry will find himself outnumbered, outclassed and dangerously susceptible to temptation. And if he screws up, his friends will die. Magic - it can get a guy killed.",
   },
   {
      asin: "B001QVHR08",
      price: 10.1,
      title: "Small Favor: The Dresden Files, Book 10",
      image: "https://m.media-amazon.com/images/I/51z+AQXe0YL.jpg",
      desc: "Harry’s life finally seems to be calming down. The White Council’s war with the vampiric Red Court is easing up, no one’s tried to kill him lately, and his eager apprentice is starting to learn real magic. For once, the future looks fairly bright. But the past casts one hell of a long shadow.  Mab, monarch of the Sidhe Winter Court, calls in an old favor from Harry. Just one small favor he can’t refuse...one that will trap Harry Dresden between a nightmarish foe and an equally deadly ally, and one that will strain his skills—and loyalties—to their very limits.",
   },
   {
      asin: "B0026HQAMC",
      price: 11.11,
      title: "Turn Coat: The Dresden Files, Book 11",
      image: "https://m.media-amazon.com/images/I/51dP1qL77WL.jpg",
      desc: "The new novel in the hit New York Times best-selling Dresden Files series.  The Warden Morgan has been accused of treason against the Wizards of the White Council - and there's only one, final punishment for that crime. He's on the run, wants his name cleared, and needs someone with a knack for backing the underdog. Someone like Harry Dresden....Now, Harry must uncover a traitor within the Council, keep a less-than-agreeable Morgan under wraps, and avoid coming under scrutiny himself. And a single mistake may cost someone his head - someone like Harry",
   },
   {
      asin: "B003FOOGG2",
      price: 12.12,
      title: "Changes: The Dresden Files, Book 12",
      image: "https://m.media-amazon.com/images/I/61w8VLUawEL.jpg",
      desc: "The new novel in the #1 New York Times best-selling Dresden Files series. Long ago, Susan Rodriguez was Harry Dresden's lover - until she was attacked by his enemies, leaving her torn between her own humanity and the bloodlust of the vampiric Red Court. Susan then disappeared to South America, where she could fight both her savage gift and those who cursed her with it.  Now Arianna Ortega, Duchess of the Red Court, has discovered a secret Susan has long kept, and she plans to use it - against Harry. To prevail this time, he may have no choice but to embrace the raging fury of his own untapped dark power. Because Harry's not fighting to save the world...He's fighting to save his child.",
   },
   {
      asin: "B00UVQEF0Y",
      price: 13.13,
      title: "Ghost Story: A Novel of the Dresden Files, Book 13",
      image: "https://m.media-amazon.com/images/I/61mGfdzmY3L.jpg",
      desc: "When an unknown someone shoots him and leaves him to die, Harry Dresden hopes he might be heading to a better place. Unfortunately being dead doesn't make Harry's life any easier.  Trapped between life and death, he learns that his friends are in serious trouble. Only by finding his murderer can he save his friends and move on - a feat that would be a lot easier if he had a body and access to his powers. Worse still are the malevolent shadows that roam Chicago, controlled by a dark entity that wants Harry to suffer even in death.  Now the late Harry Dresden will have to pull off the ultimate trick without using any magic - or face an eternity as just another lost soul....",
   },
   {
      asin: "B00A2ZIR7G",
      price: 14.14,
      title: "Cold Days: The Dresden Files, Book 14",
      image: "https://m.media-amazon.com/images/I/61jVQ6CHxcL.jpg",
      desc: "After being murdered by a mystery assailant, navigating his way through the realm between life and death, and being brought back to the mortal world, Harry realizes that maybe death wasn’t all that bad - because he is no longer Harry Dresden, Chicago’s only professional wizard. He is now Harry Dresden, Winter Knight to Mab, the Queen of Air and Darkness.  After Harry had no choice but to swear his fealty, Mab wasn’t about to let something as petty as death steal away the prize she had sought for so long. And now, her word is his command, no matter what she wants him to do, no matter where she wants him to go, and no matter who she wants him to kill. Guess which one Mab wants first?  Of course, it won’t be an ordinary, everyday assassination. Mab wants her newest minion to pull off the impossible: kill an immortal. No problem there, right? And to make matters worse, there exists a growing threat to an unfathomable source of magic that could land Harry in the sort of trouble that will make death look like a holiday.  Beset by enemies new and old, Harry must gather his friends and allies, prevent the annihilation of countless innocents, and find a way out of his eternal subservience before his newfound powers claim the only thing he has left to call his own… his soul.",
   },
   {
      asin: "B00JDQ7X8O",
      price: 15.15,
      title: "Skin Game: A Novel of the Dresden Files, Book 15",
      image: "https://m.media-amazon.com/images/I/61rdn5WudXL.jpg",
      desc: "Harry Dresden, Chicago's only professional wizard, is about to have a very bad day.…  Because as Winter Knight to the Queen of Air and Darkness, Harry never knows what the scheming Mab might want him to do. Usually, it’s something awful.  He doesn’t know the half of it.…  Mab has just traded Harry's skills to pay off one of her debts. And now he must help a group of supernatural villains - led by one of Harry's most dreaded and despised enemies, Nicodemus Archleone - to break into the highest-security vault in town, so that they can then access the highest-security vault in the Nevernever.  It's a smash-and-grab job to recover the literal Holy Grail from the vaults of the greatest treasure hoard in the supernatural world - which belongs to the one and only Hades, Lord of the freaking Underworld and generally unpleasant character. Worse, Dresden suspects that there is another game afoot that no one is talking about. And he's dead certain that Nicodemus has no intention of allowing any of his crew to survive the experience. Especially Harry.  Dresden's always been tricky, but he's going to have to up his backstabbing game to survive this mess - assuming his own allies don’t end up killing him before his enemies get the chance.…",
   },
   {
      asin: "B082YH6QL4",
      price: 16.16,
      title: "Peace Talks: Dresden Files, Book 16",
      image: "https://m.media-amazon.com/images/I/51fO-ekMn2L.jpg",
      desc: "Harry Dresden is back and ready for action, in the new entry in the number-one New York Times best-selling Dresden Files.   When the supernatural nations of the world meet up to negotiate an end to ongoing hostilities, Harry Dresden, Chicago's only professional wizard, joins the White Council's security team to make sure the talks stay civil. But can he succeed, when dark political manipulations threaten the very existence of Chicago - and all he holds dear?",
   },
   {
      asin: "B086PWKP9J",
      price: 17.17,
      title: "Battle Ground: Dresden Files, Book 17",
      image: "https://m.media-amazon.com/images/I/5111yqXG8KL.jpg",
      desc: "Things are about to get serious for Harry Dresden, Chicago’s only professional wizard, in the next entry in the number-one New York Times best-selling Dresden Files.  Harry has faced terrible odds before. He has a long history of fighting enemies above his weight class. The Red Court of vampires. The fallen angels of the Order of the Blackened Denarius. The Outsiders.   But this time it’s different. A being more powerful and dangerous on an order of magnitude beyond what the world has seen in a millennium is coming. And she’s bringing an army. The Last Titan has declared war on the city of Chicago and has come to subjugate humanity, obliterating any who stand in her way.   Harry’s mission is simple but impossible: Save the city by killing a Titan. And the attempt will change Harry’s life, Chicago, and the mortal world forever.",
   },
];

export default bookArray;
